default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: <%= ENV['DB_USERNAME'] %>
  database: port-mb_development

test: &test
  <<: *default
  database: port-mb_test

production:
  <<: *default
  database: port-mb_production

cucumber:
  <<: *test
