# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c250fe4e08749b1ad05e601c8d2b038e8493d5fd44c7bcfd5b1ac26a602039d2ca87fafeed79f00daa59277f8e10d7bb5c801ec517caf0598bb3ad95fdcf3ded

test:
  secret_key_base: d10a7145bb8bf6d82295b92d5f25a07fd738bc981a1be84dbff036b1b761b74e5e70fe9468b98b4f09f021fca33856a9b9622fe00b96d701cb4116b6eeee4bea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
